package:
  name: ros-noetic-tf2-web-republisher
  version: 0.3.2
about:
  home: http://ros.org/wiki/tf2_web_republisher
  license:
    - BSD
  summary: Republishing of Selected TFs
  maintainers:
    - Julius Kammer (jkammerl@willowgarage.com)
extra:
  recipe-maintainers:
    - robostack
build:
  number: 0
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
source:
  url: https://github.com/RobotWebTools/tf2_web_republisher/archive/0.3.2.tar.gz
  sha256: a0a6278937fe72eb6e30b62ad39c8f52f9cf5ddc6b61e43490d0d63749037a29
  folder: ros-noetic-tf2-web-republisher/src/work
  patches:
    - sel(unix): ros-noetic-tf2-web-republisher.patch
requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - python
    - ros-noetic-catkin
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-roscpp
    - ros-noetic-tf2-ros
    - ros-noetic-tf
    - ros-noetic-message-generation
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-roscpp
    - ros-noetic-tf2-ros
    - ros-noetic-tf
    - ros-noetic-message-runtime
    - ros-noetic-rospy
    - ros-noetic-rostest
  run:
    - python
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-roscpp
    - ros-noetic-tf2-ros
    - ros-noetic-tf
    - ros-noetic-message-runtime
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-roscpp
    - ros-noetic-tf2-ros
    - ros-noetic-tf
    - ros-noetic-message-runtime
