package:
  name: ros-noetic-image-view
  version: 1.15.3
source:
  git_url: https://github.com/ros-gbp/image_pipeline-release.git
  git_rev: release/noetic/image_view/1.15.3-1
  folder: ros-noetic-image-view/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(unix): "{{ cdt('mesa-libgl-devel') }}"
    - sel(unix): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
  host:
    - epoxy
    - glib
    - gtk3
    - harfbuzz
    - libglib
    - libxcb
    - pthread-stubs
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-camera-calibration-parsers
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-message-generation
    - ros-noetic-nodelet
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
    - ros-noetic-std-srvs
    - ros-noetic-stereo-msgs
    - xorg-libxau
    - xorg-libxcomposite
    - xorg-libxcursor
    - xorg-libxdamage
    - xorg-libxi
    - xorg-libxinerama
    - xorg-libxrandr
    - xorg-libxtst
    - xorg-xineramaproto
  run:
    - epoxy
    - glib
    - gtk3
    - harfbuzz
    - libglib
    - libxcb
    - pthread-stubs
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-camera-calibration-parsers
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-nodelet
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-std-srvs
    - xorg-libxau
    - xorg-libxcomposite
    - xorg-libxcursor
    - xorg-libxdamage
    - xorg-libxi
    - xorg-libxinerama
    - xorg-libxrandr
    - xorg-libxtst
    - xorg-xineramaproto
