package:
  name: ros-noetic-grid-map-filters
  version: 1.6.4
source:
  git_url: https://github.com/anybotics/grid_map-release.git
  git_rev: release/noetic/grid_map_filters/1.6.4-1
  folder: ros-noetic-grid-map-filters/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
  host:
    - gmock
    - gtest
    - libopencv 4.5
    - py-opencv 4.5
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
    - ros-noetic-filters
    - ros-noetic-grid-map-core
    - ros-noetic-grid-map-msgs
    - ros-noetic-grid-map-ros
    - tbb
    - tbb-devel
  run:
    - libopencv
    - py-opencv
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-filters
    - ros-noetic-grid-map-core
    - ros-noetic-grid-map-msgs
    - ros-noetic-grid-map-ros
    - tbb
    - tbb-devel
